AWSTemplateFormatVersion: '2010-09-09'

Resources:

  AppBucket:
    Type: AWS::S3::Bucket

  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      IamInstanceProfile: LabInstanceProfile
